name:         my-taffybar
version:      0.0.1.0
github:       "pjan/taffybar"
license:      MIT
license-file: LICENSE.md
author:       "pjan vandaele"
maintainer:   "pjan@pjan.io"
copyright:    "2018 pjan vandaele"

description:  Please see the README on Github at <https://github.com/pjan/taffybar#readme>

flags:
  documentation:
    description: link documentation to source
    manual: yes
    default: no

extra-source-files:
- package.yaml
- LICENSE.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- taffybar

library:
  source-dirs: lib

  when:
  - condition: flag(documentation)
    dependencies: hscolour

executables:
  my-taffybar-exe:
    main:        taffybar.hs
    source-dirs: ./.
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-taffybar

